### ISSUE TITLE
Make ready for general use

### ISSUE THREAD

**Issue by roryc89** [OxfordAbstracts/purescript-graphql-client#21]
List of things to make it reasonable to make this package consumable for users outside of Oxford Abstracts

- [x] Make generated code work with purty https://github.com/OxfordAbstracts/purescript-graphql-client/issues/17
- [x] Give option to return errors along with result  https://github.com/OxfordAbstracts/purescript-graphql-client/issues/15
- [x] Add Codegen config file https://github.com/OxfordAbstracts/purescript-graphql-client/issues/13
- [x] Add docs https://github.com/OxfordAbstracts/purescript-graphql-client/issues/11

**Comment by roryc89** [comment]
Done
